version: "3.7"
services:
  upstarts-hp:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ..:/app/:delegated
    container_name: upstarts-hp